### ISSUE TITLE
Suggest to include Prelude.ls in this package.

### ISSUE THREAD

**Issue by wuxianliang** [Dessix/Meteor-LiveScript#1]
Dear @Dessix 

This pacakge is just in time. And I have used this package for months. Because of the lack of new Prelude.ls in meteor community, I have to update prelude.ls locally by hands. So I think it would be nice to include Prelude.ls in this package. Thank you very much.

**Comment by Dessix** [comment]
Being that prelude has minimal conflicts and much of its behavior directly derives from LiveScript functionality, I have taken your suggestion.
See c9567408bfe9d85fc4e2276750ea6115f76ddc68.
