### ISSUE TITLE
Great package

### ISSUE THREAD

**Issue by drozzy** [Dessix/Meteor-LiveScript#2]
Just wanted to say that this works beautifully!
I hope you find a way to keep it updated.

**Comment by Dessix** [comment]
If a new version of a dependency comes out and you want it integrated, feel free to either post an issue here requesting an update, or do me a favor and pull-request the changes. Either way, I'll respond within 2 days as long as I'm alive.

**Comment by wuxianliang** [comment]
@Dessix  prelude.ls 1.1.2 and livescript 1.4.0 have come out. Thank you very much!

**Comment by Dessix** [comment]
Published dessix:livescript-compiler@0.2.0 in 1c8e586bd2c9c9c7b35ef74ca6da6404c5a1298c.
