### ISSUE TITLE
Depreciation warning

### ISSUE THREAD

**Issue by drozzy** [Dessix/Meteor-LiveScript#3]
Nothing major it seems, just a warning. No idea what it means...

`language-livescript (1 deprecation)
Store package settings files in the settings/ directory instead of scoped-properties/
Called 1 timeCreate Issue on language-livescript repo
Package.loadSettings - C:\Users\Andriy\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:586:9
<unknown> - C:\Users\Andriy\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:188:43
Package.measure - C:\Users\Andriy\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:167:15
Package.load - C:\Users\Andriy\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:181:12`

**Comment by Dessix** [comment]
Is this issue still occurring with the updated livescript version?

**Comment by Dessix** [comment]
Project is now abandoned as it is severely outdated.
