### ISSUE TITLE
Any plan to add compile to .json  ?

### ISSUE THREAD

**Issue by daveeel** [Dessix/Meteor-LiveScript#4]
i.e. compile .json.ls -> .json

Thanks

**Comment by Dessix** [comment]
Is that even a format? I've never heard of Json.ls.

**Comment by Dessix** [comment]
After a bit of looking around, I've found a means of compiling it as json programmatically, but I am unsure how this should be properly registered with Meteor. Here's some code you can work off of that would be placed in `plugins/compileLiveScript.js`, but I'm not sure if it works, hence I am unwilling to push it to the plugin repository.

```

var handler = function (compileStep) {
    var source = compileStep.read().toString('utf8');
    var outputFile = compileStep.inputPath + ".json";

    options = {
        json: true
    };

    try {
        var output = livescript.compile(source, options);
    } catch (e) {
        throw new Error(
            compileStep.inputPath + ':' +
            (e.location ? (e.location.first_line + ': ') : ' ') +
            e.message
        );
    }

    compileStep.addAsset({
        path: outputFile,
        data: output
    });
};

Plugin.registerSourceHandler('json.ls', handler);

```

If you know how to locally test these packages, feel free to modify that as needed and submit a pull request and I'll push it to the repository.

**Comment by daveeel** [comment]
lsc -c file.json.ls will compile to file.json by default
That doesn't seem to work automatically as transpiler package.

Will try test. Thanks.

**Comment by daveeel** [comment]
As per my test, { json: true } is not a supported option for .compile(). The .json.ls is still treated as .ls, thus unable to compile. Checking with the LiveScript guys...

**Comment by daveeel** [comment]
Confirmed that {json:true} works. However the outfile .json ends up located in the compiled folder, probably not the general use case. Thanks anyway.
