### ISSUE TITLE
Can i  use require without extension?

### ISSUE THREAD

**Issue by focused** [Dessix/Meteor-LiveScript#5]
```
# works
require! "/imports/Application.ls"

# does not work
require! "/imports/Application"
```

**Comment by focused** [comment]
It's annoying to write `require "/imports/my-lib/index.ls"` instead of `require "/imports/my-lib"`

**Comment by Dessix** [comment]
This extension is terribly outdated, you'd be better off writing your own with Meteor's new systems, and I am waiting until full-ES6 support is standard across the NPM community before I bother working in Meteor again. I'm sorry :disappointed:
